[package]
name = "raytracer"
version = "0.1.0"
authors = ["swlynch <swlynch@uwaterloo.ca>"]

[lib]
name = "raytracer"
path = "src/lib.rs"

[profile.release]
lto = true

[dependencies]
rand         = "0.4.1"
image        = "0.18.0"
threadpool   = "1.7.0"
num_cpus     = "1.0"
gradient     = { path = "../gradient" }
pbr          = "1.0"
#dyon         = "0.28"
glslvec      = { path = "../glslvec" }
