[package]
name = "raytracer"
version = "0.1.0"
authors = ["swlynch <swlynch@uwaterloo.ca>"]

[lib]
name = "raytracer"
path = "src/lib.rs"

[dependencies]
rand = "0.4.1"
image = "0.18.0"
threadpool = "1.7.0"
num_cpus = "1.0"

serde_json = "1.0"

[dependencies.cgmath]
version = "0.16"
features = ["swizzle"]
